from nr_common_test_model.resources.records.config import (
    NrCommonTestModelResourceConfig,
)
from nr_common_test_model.resources.records.resource import NrCommonTestModelResource
from nr_common_test_model.services.records.config import NrCommonTestModelServiceConfig
from nr_common_test_model.services.records.service import NrCommonTestModelService

NR_COMMON_TEST_MODEL_RECORD_RESOURCE_CONFIG = NrCommonTestModelResourceConfig


NR_COMMON_TEST_MODEL_RECORD_RESOURCE_CLASS = NrCommonTestModelResource


NR_COMMON_TEST_MODEL_RECORD_SERVICE_CONFIG = NrCommonTestModelServiceConfig


NR_COMMON_TEST_MODEL_RECORD_SERVICE_CLASS = NrCommonTestModelService
