from nr_theses_test_model.resources.records.config import (
    NrThesesTestModelResourceConfig,
)
from nr_theses_test_model.resources.records.resource import NrThesesTestModelResource
from nr_theses_test_model.services.records.config import NrThesesTestModelServiceConfig
from nr_theses_test_model.services.records.service import NrThesesTestModelService

NR_THESES_TEST_MODEL_RESOURCE_CONFIG_NR_THESES_TEST_MODEL = (
    NrThesesTestModelResourceConfig
)
NR_THESES_TEST_MODEL_RESOURCE_CLASS_NR_THESES_TEST_MODEL = NrThesesTestModelResource
NR_THESES_TEST_MODEL_SERVICE_CONFIG_NR_THESES_TEST_MODEL = (
    NrThesesTestModelServiceConfig
)
NR_THESES_TEST_MODEL_SERVICE_CLASS_NR_THESES_TEST_MODEL = NrThesesTestModelService
